services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - microblogging-network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microblogging
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:17-alpine
    expose:
      - 5432
    networks:
      - microblogging-network
    environment:
      POSTGRES_DB: microblogging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  microblogging-network:
